[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pvs-hass-mqtt"
version = "0.0.1"
authors = [
  { name="Kevin P. Fleming", email="kevin@km6g.us" },
]
description = "An MQTT-based integration for SunPower PVS and Home Assistant"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]

[project.urls]
"Homepage" = "https://github.com/kpfleming/pvs-hass-mqtt"
"Bug Tracker" = "https://github.com/kpfleming/pvs-hass-mqttt/issues"
