pvs:
  type: dict
  allow_unknown: True
  minlength: 1
  required: True
  keysrules:
    type: string
  valuesrules:
    type: dict
    schema:
      url:
        type: string
        required: True
      poll_interval:
        type: integer
        default: 60
        min: 30

array:
  type: dict
  allow_unknown: True
  minlength: 1
  required: True
  keysrules:
    type: string
  valuesrules:
    type: dict
    schema:
      panel:
        type: list
        schema:
          type: string
        minlength: 1
        required: True
      azimuth:
        type: float
        min: 0
        max: 360
      tilt:
        type: float
        min: 0
        max: 90

mqtt:
  type: dict
  required: True
  schema:
    broker:
      type: string
      required: True
    port:
      type: integer
      required: True
      default: 1883
      min: 1
      max: 65535
    username:
      type: string
    password:
      type: string
    client_id:
      type: string
    keep_alive:
      type: integer
      default: 30
      min: 1
    qos:
      type: integer
      default: 0
      min: 0
      max: 2
    hass_topic_prefix:
      type: string
      default: homeassistant
      required: true
