name: "Run linter checks"
inputs:
  lintly_token:
    required: true
runs:
  using: "composite"
  steps:
  - name: run lint tests
    run: hatch --data-dir /root/hatch run lint-action:lint
    shell: bash
    env:
      LINTLY_API_KEY: ${{ inputs.lintly_token }}
