name: "Run linter checks"
inputs:
  lintly_token:
    required: true
runs:
  using: "composite"
  steps:
  - name: run lint tests
    run: env HATCH_ENV_TYPE_VIRTUAL_PATH=/root/hatch/lint-action hatch run lint-action:lint
    shell: bash
    env:
      LINTLY_API_KEY: ${{ inputs.lintly_token }}
