name: CI

on:
  push:
    branches:
    - main
    paths:
    - 'src/*.py'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_*_image.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - 'src/*.py'
    - 'tox.ini'
    - 'workflow-support/test-*.yml'
    - 'workflow-support/make_*_image.sh'
    - '.github/workflows/ci.yml'
    - '.github/actions/*/action.yml'
  schedule:
    - cron: "35 4 * * 6"

env:
  registry_base: 'quay.io/phm-test-images'

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      # workaround to make registry_base available in jobs
      registry_base: ${{ env.registry_base }}
    steps:
    - uses: actions/checkout@v3
    - id: preflight
      uses: ./.github/actions/ci-preflight
  image-tox:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/make-tox-image
      if: needs.preflight.outputs.need_image == 'true'
      with:
        image_name: ${{ needs.preflight.outputs.registry_base }}/tox:${{ needs.preflight.outputs.image_tag }}
        quay_username: ${{ secrets.QUAY_BOT_NAME }}
        quay_password: ${{ secrets.QUAY_BOT_PASSWORD }}
  test:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    - image-tox
    strategy:
      matrix:
        python: [py38, py39, py310, py311]
      fail-fast: false
    container:
      image: docker://${{ needs.preflight.outputs.registry_base }}/tox:${{ needs.preflight.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v3
    - name: run tests
      run: tox -e${{ matrix.python }} --workdir /root/tox
