name: Lint checks

on:
  pull_request:
    branches:
    - main
    paths:
    - 'pyproject.toml'
    - 'src/**.py'
    - '.github/workflows/lint.yml'
    - '.github/actions/preflight/action.yml'
    - '.github/actions/lint/action.yml'

env:
  registry_base: 'quay.io/km6g-ci-images'

jobs:
  preflight:
    runs-on: ubuntu-20.04
    outputs:
      need_image: ${{ steps.preflight.outputs.need_image }}
      image_tag: ${{ steps.preflight.outputs.image_tag }}
      # workaround to make registry_base available in jobs
      registry_base: ${{ env.registry_base }}
    steps:
    - uses: actions/checkout@v3
    - id: preflight
      uses: ./.github/actions/preflight
    - name: ensure image has been created
      uses: lewagon/wait-on-check-action@v1.1.2
      if: github.event_name != 'pull_request'
      with:
        ref: ${{ github.sha }}
        check-name: ci-image
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
    - name: ensure image has been created
      uses: lewagon/wait-on-check-action@v1.1.2
      if: github.event_name == 'pull_request'
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        check-name: ci-image
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30
  lint:
    runs-on: ubuntu-20.04
    needs:
    - preflight
    container:
      image: docker://${{ needs.preflight.outputs.registry_base }}/pvs-hass-mqtt:${{ needs.preflight.outputs.image_tag }}
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/lint
